from App.Commands import *
from App.Commands import dinitaks

data = {
'kireikharisma' : kireikharisma,
'anamilatul' : anamilatul,
'Rifqi2000' : Rifqi2000,
'lilikwn': lilikwn,
'RoyalWeaboo' : RoyalWeaboo,
'Villaneuvo' : Villaneuvo,
'mazc0de' : mazc0de,
'fachryaa' : fachryaa,
'ivannoard' : ivannoard,
'safiraauliar' : safiraauliar,
'rofinoorsalim' : rofinoorsalim,
'Dewasurya16' : Dewasurya16,
'TrisatyaProgramming' : TrisatyaProgramming,
'ilse31':ilse31,
'bejjoeqq' : bejjoeqq,
'shironim': shironim,
'semnadtsat' : semnadtsat,
'derynm' : derynm,
'xzarras'   : xzarras,
'NecroYash' : NecroYash,
'enricozd' : enricozd,
'Alaik1924' : Alaik1924,
'Akhdan' : Akhdan,
"wmprawiro" : wmprawiro,
"badroll" : badroll,
'maulanaaghnii' : maulanaaghnii,
'rama1277' : rama1277,
'mkuadrat' : mkuadrat,
'bdddbags': bdddbags,
'MirzaRazzaq': MirzaRazzaq,
'yogasnaper' : yogasnaper,
'arijit' : arijit,
'kurniawanflix' : kurniawanflix,
'nurulisma' : nurulisma,
'dinitaks' : dinitaks,
}
