from App.Commands import *


data = {
'kireikharisma' : kireikharisma,
'anamilatul' : anamilatul,
'Rifqi2000' : Rifqi2000,
'lilikwn': lilikwn,
'RoyalWeaboo' : RoyalWeaboo,
'Villaneuvo' : Villaneuvo,
'mazc0de' : mazc0de,
'fachryaa' : fachryaa,
'ivannoard' : ivannoard,
'safiraauliar' : safiraauliar,
'rofinoorsalim' : rofinoorsalim,
'Dewasurya16' : Dewasurya16,
'TrisatyaProgramming' : TrisatyaProgramming,
'ilse31':ilse31,
'Itsuka22' : Itsuka22,
'bejjoeqq' : bejjoeqq,
'shironim': shironim,
'semnadtsat' : semnadtsat,
'derynm' : derynm,
'xzarras'   : xzarras,
'NecroYash' : NecroYash,
'enricozd' : enricozd,
'Alaik1924' : Alaik1924,
'Akhdan' : Akhdan,
"wmprawiro" : wmprawiro,
"badroll" : badroll,
'maulanaaghnii' : maulanaaghnii,
'rama1277' : rama1277,
'mkuadrat' : mkuadrat,
'bdddbags': bdddbags,
'MirzaRazzaq': MirzaRazzaq,
'yogasnaper' : yogasnaper,
'arijit' : arijit,
'kurniawanflix' : kurniawanflix,
'bejjo2' : bejjo2,
'nurulisma' : nurulisma,
'dinitaks' : dinitaks,
'primadya' : primadya,
'yahyawildan' : yahyawildan,
'Bejo55': Bejo55,
'syekhu26' : syekhu26,
'iamnotgiraffe' : iamnotgiraffe,
'bimarakajati' : bimarakajati,
'hafizxd' : hafizxd,
'Zdan009' : Zdan009,
'husin14' : husin14,
'PBWim' : PBWim,
'ilhamNR' : ilhamNR,
'snowfluke' : snowfluke,
'novanauliazami': novanauliazami
}
